replicaCount: 1

image:
  repository: favourite-service
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8800

containerPort: 8800

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_ZIPKIN_BASE_URL
    value: http://zipkin:9411/
  - name: eureka.client.service-url.defaultZone
    value: http://discovery:8761/eureka
  - name: EUREKA_INSTANCE_HOSTNAME
    value: favourite-service
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "true"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "true"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"

readinessProbe:
  path: /favourite-service/actuator/health
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 2

livenessProbe:
  path: /favourite-service/actuator/health
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 3
