fullnameOverride: discovery

replicaCount: 1

image:
  repository: service-discovery
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8761

readinessProbe:
  path: /actuator/health
  port: 8761
  initialDelaySeconds: 60
  periodSeconds: 30

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_ZIPKIN_BASE_URL
    value: http://zipkin:9411/
