replicaCount: 1

image:
  repository: openzipkin/zipkin
  tag: latest
  pullPolicy: IfNotPresent  

service:
  # Cluster IP configuration define that the service is only accesible from cluster 
  type: LoadBalancer
  port: 9411

readinessProbe:
  path: /health
  port: 9411
  initialDelaySeconds: 30
  periodSeconds: 10
