fullnameOverride: payment-service

replicaCount: 1

image:
  repository: payment-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8400

readinessProbe:
  path: /payment-service/actuator/health
  port: 8400
  initialDelaySeconds: 10
  periodSeconds: 30

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_ZIPKIN_BASE_URL
    value: http://zipkin:9411/
  - name: eureka.client.service-url.defaultZone
    value: http://discovery:8761/eureka
  - name: EUREKA_INSTANCE_HOSTNAME
    value: payment-service
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "true"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "true"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
