version: '3.8'

services:
  zipkin-container:
    image: openzipkin/zipkin
    container_name: zipkin-container
    ports:
      - "9411:9411"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  service-discovery-container:
    image: selimhorri/service-discovery-ecommerce-boot:0.1.0
    container_name: service-discovery-container
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - zipkin-container

  cloud-config-container:
    image: selimhorri/cloud-config-ecommerce-boot:0.1.0
    container_name: cloud-config-container
    ports:
      - "9296:9296"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=cloud-config-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=10
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=30
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITY_ZONES_DEFAULT=defaultZone
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9296/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: on-failure

  api-gateway-container:
    image: selimhorri/api-gateway-ecommerce-boot:0.1.0
    container_name: api-gateway-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=cloud-config-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=10
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=30      
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITY_ZONES_DEFAULT=defaultZone
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

  proxy-client-container:
    image: selimhorri/proxy-client-ecommerce-boot:0.1.0
    container_name: proxy-client-container
    ports:
      - "8900:8900"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=proxy-client-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

  order-service-container:
    image: selimhorri/order-service-ecommerce-boot:0.1.0
    container_name: order-service-container
    ports:
      - "8300:8300"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=order-service-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

  payment-service-container:
    image: selimhorri/payment-service-ecommerce-boot:0.1.0
    container_name: payment-service-container
    ports:
      - "8400:8400"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=payment-service-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

  product-service-container:
    image: selimhorri/product-service-ecommerce-boot:0.1.0
    container_name: product-service-container
    ports:
      - "8500:8500"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=product-service-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

  shipping-service-container:
    image: selimhorri/shipping-service-ecommerce-boot:0.1.0
    container_name: shipping-service-container
    ports:
      - "8600:8600"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=shipping-service-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

  user-service-container:
    image: selimhorri/user-service-ecommerce-boot:0.1.0
    container_name: user-service-container
    ports:
      - "8700:8700"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=user-service-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

  favourite-service-container:
    image: selimhorri/favourite-service-ecommerce-boot:0.1.0
    container_name: favourite-service-container
    ports:
      - "8800:8800"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - eureka.client.service-url.defaultZone=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=favourite-service-container
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    networks:
      - microservices-network
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy
    restart: on-failure

networks:
  microservices-network:
    driver: bridge
    name: microservices-network